// every Roblox service, as declared by Roblox's own API dump
//
// the table is generated by scripts/api-dump.ts; this only reads it

use std::collections::HashMap;
use std::sync::OnceLock;

const TABLE: &str = include_str!("services.txt");

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemberKind {
    Property,
    Event,
    Function,
    Callback,
}

#[derive(Debug, Clone, Copy)]
pub struct Member {
    pub kind: MemberKind,
    pub name: &'static str,
    // a property's value type, or a function's return type
    pub type_name: &'static str,
    pub deprecated: bool,
    pub read_only: bool,
}

#[derive(Debug)]
pub struct Service {
    pub name: &'static str,
    pub superclass: &'static str,
    pub tags: &'static str,
    pub members: HashMap<&'static str, Member>,
}

impl Service {
    pub fn not_creatable(&self) -> bool {
        self.tags.split(',').any(|tag| tag == "NotCreatable")
    }
}

struct Table {
    version: &'static str,
    // declaration order, so a listing is stable
    services: Vec<Service>,
    by_name: HashMap<&'static str, usize>,
}

static TABLE_PARSED: OnceLock<Table> = OnceLock::new();

fn parsed() -> &'static Table {
    TABLE_PARSED.get_or_init(|| {
        let mut version = "unknown";
        let mut services: Vec<Service> = Vec::new();

        for line in TABLE.lines() {
            if let Some(rest) = line.strip_prefix("# dump ") {
                version = rest.split(',').next().unwrap_or("unknown").trim();
                continue;
            }
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            if let Some(rest) = line.strip_prefix("service ") {
                let mut parts = rest.split(' ');
                let name = parts.next().unwrap_or("");
                let superclass = parts.next().unwrap_or("Instance");
                let tags = parts.next().unwrap_or("-");
                services.push(Service {
                    name,
                    superclass,
                    tags,
                    members: HashMap::new(),
                });
                continue;
            }
            let Some(service) = services.last_mut() else {
                continue;
            };
            let mut parts = line.trim().split(' ');
            let kind = match parts.next() {
                Some("property") => MemberKind::Property,
                Some("event") => MemberKind::Event,
                Some("function") => MemberKind::Function,
                Some("callback") => MemberKind::Callback,
                _ => continue,
            };
            let name = parts.next().unwrap_or("");
            let type_name = if kind == MemberKind::Event {
                "nil"
            } else {
                parts.next().unwrap_or("nil")
            };
            let tags = parts.next().unwrap_or("");
            service.members.insert(
                name,
                Member {
                    kind,
                    name,
                    type_name,
                    deprecated: tags.contains("deprecated"),
                    read_only: tags.contains("readonly"),
                },
            );
        }

        let by_name = services
            .iter()
            .enumerate()
            .map(|(index, service)| (service.name, index))
            .collect();
        Table {
            version,
            services,
            by_name,
        }
    })
}

// the dump this table was generated from
pub fn version() -> &'static str {
    parsed().version
}

pub fn services() -> &'static [Service] {
    &parsed().services
}

pub fn service(name: &str) -> Option<&'static Service> {
    let table = parsed();
    let index = *table.by_name.get(name)?;
    table.services.get(index)
}

pub fn is_service(name: &str) -> bool {
    parsed().by_name.contains_key(name)
}

// every service a script can ask for: the hand-written ones first, then the generated table
pub fn service_names() -> Vec<&'static str> {
    let mut names: Vec<&'static str> = crate::classes::service_names().collect();
    for service in services() {
        if !names.contains(&service.name) {
            names.push(service.name);
        }
    }
    names
}

// a member on the class or anything it inherits from
pub fn member(class: &str, name: &str) -> Option<&'static Member> {
    let mut current = Some(class.to_string());
    while let Some(klass) = current {
        if let Some(found) = service(&klass).and_then(|service| service.members.get(name)) {
            return Some(found);
        }
        current = crate::classes::descriptor(&klass)
            .and_then(|descriptor| descriptor.superclass)
            .map(str::to_string)
            .filter(|parent| parent != &klass);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_the_generated_table() {
        assert!(services().len() > 200, "{} services", services().len());
        assert!(version().starts_with("version-"), "dump {}", version());
    }

    #[test]
    fn finds_members_through_the_class_chain() {
        let get = member("HttpService", "GetAsync").expect("GetAsync");
        assert_eq!(get.kind, MemberKind::Function);
        assert_eq!(get.type_name, "string");

        let event = member("MarketplaceService", "PromptGamePassPurchaseFinished")
            .expect("PromptGamePassPurchaseFinished");
        assert_eq!(event.kind, MemberKind::Event);

        let property = member("HttpService", "HttpEnabled").expect("HttpEnabled");
        assert_eq!(property.kind, MemberKind::Property);
        assert_eq!(property.type_name, "bool");

        assert!(member("HttpService", "NotAMember").is_none());
        assert!(member("DataStoreService", "GetDataStore").is_some());
    }

    #[test]
    fn knows_services_that_are_not_hand_written() {
        assert!(is_service("HttpService"));
        assert!(is_service("GuiService"));
        assert!(is_service("DataStoreService"));
        assert!(!is_service("Part"));
        assert!(!is_service("NotAService"));
    }
}
