// regenerates the service table the runtime simulates from Roblox's own API dump
//
// usage:
//   node scripts/api-dump.ts                     fetch the current Studio dump
//   node scripts/api-dump.ts --dump <file>       use a dump already on disk
//   node scripts/api-dump.ts --out <file>        write somewhere else

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_OUT = join(repoRoot, "crates", "microstudio-datamodel", "src", "api", "services.txt");

interface DumpMember {
  MemberType: "Function" | "Event" | "Property" | "Callback";
  Name: string;
  Tags?: string[];
  ValueType?: { Name?: string };
  ReturnType?: { Name?: string };
  Parameters?: { Name: string; Type: { Name?: string } }[];
}

interface DumpClass {
  Name: string;
  Superclass?: string;
  Tags?: string[];
  Members?: DumpMember[];
}

interface Dump {
  Classes: DumpClass[];
}

const args = process.argv.slice(2);
function flag(name: string): string | undefined {
  const index = args.indexOf(name);
  return index === -1 ? undefined : args[index + 1];
}

async function readDump(): Promise<{ dump: Dump; version: string }> {
  const local = flag("--dump");
  if (local !== undefined) {
    return {
      dump: JSON.parse(readFileSync(resolve(local), "utf8")) as Dump,
      version: "local file",
    };
  }

  const version = (
    await (await fetch("https://setup.rbxcdn.com/versionQTStudio")).text()
  ).trim();
  const url = `https://setup.rbxcdn.com/${version}-API-Dump.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${url} answered ${response.status}`);
  }
  return { dump: (await response.json()) as Dump, version };
}

// the dump's type names, mapped onto what the runtime stores
function propertyType(member: DumpMember): string {
  const name = member.ValueType?.Name ?? "nil";
  switch (name) {
    case "bool":
      return "bool";
    case "int":
    case "int64":
    case "float":
    case "double":
    case "number":
      return "number";
    case "string":
    case "Content":
    case "ContentId":
      return "string";
    case "Vector3":
      return "vector3";
    case "Vector2":
      return "vector2";
    case "CFrame":
      return "cframe";
    case "Color3":
      return "color3";
    case "BrickColor":
      return "brickcolor";
    case "Instance":
      return "instance";
    case "Enum":
    case "EnumItem":
      return "enum";
    default:
      // Array, Dictionary, Rect, Font, Secret, ...: any value, nil by default
      return "any";
  }
}

function functionReturn(member: DumpMember): string {
  return member.ReturnType?.Name ?? "nil";
}

// one line per member, so the parser on the other side stays trivial
function memberLine(member: DumpMember): string {
  const deprecated = member.Tags?.includes("Deprecated") === true;
  const readOnly = member.Tags?.includes("ReadOnly") === true;
  const tags = [deprecated ? "deprecated" : "", readOnly ? "readonly" : ""]
    .filter((tag) => tag.length > 0)
    .join(",");
  const suffix = tags.length === 0 ? "" : ` ${tags}`;

  switch (member.MemberType) {
    case "Property":
      return `${member.Name} ${propertyType(member)}${suffix}`;
    case "Event":
      return `${member.Name}${suffix}`;
    case "Function":
    case "Callback":
      return `${member.Name} ${functionReturn(member)}${suffix}`;
    default:
      return `${member.Name}${suffix}`;
  }
}

async function main(): Promise<number> {
  const { dump, version } = await readDump();
  const services = dump.Classes.filter((entry) => entry.Tags?.includes("Service") === true);
  services.sort((left, right) => left.Name.localeCompare(right.Name));

  const lines: string[] = [
    `# microstudio service table, generated by scripts/api-dump.ts`,
    `# dump ${version}, ${services.length} services, do not edit by hand`,
  ];

  for (const service of services) {
    const tags = (service.Tags ?? []).filter((tag) => tag !== "Service");
    lines.push(
      `service ${service.Name} ${service.Superclass ?? "Instance"} ${tags.join(",") || "-"}`,
    );
    for (const member of service.Members ?? []) {
      lines.push(`  ${member.MemberType.toLowerCase()} ${memberLine(member)}`);
    }
  }

  const out = resolve(flag("--out") ?? DEFAULT_OUT);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, `${lines.join("\n")}\n`);

  const members = services.reduce((total, service) => total + (service.Members?.length ?? 0), 0);
  console.log(`${services.length} services, ${members} members -> ${out}`);
  if (!existsSync(out)) {
    return 1;
  }
  return 0;
}

process.exitCode = await main();
